export default {
  CONTENT_TYPE: {
    COMICS: 'FETCH_COMICS',
    CHARACTERS: 'FETCH_CHARACTERS'
  },
  FILTER_BY: 'FILTER_BY',
  FILTER_COMICS_BY_CHARACTER: 'FILTER_COMICS_BY_CHARACTER',
  FILTER_COMICS_BY_SERIES: 'FILTER_COMICS_BY_SERIES',

  FETCH_CHAR_BY_ID: 'FETCH_CHAR_BY_ID',
  FETCH_COMIC_BY_ID: 'FETCH_COMIC_BY_ID',

  SAVE_LOCATION: 'SAVE_LOCATION'
};
