export default {
  CONTENT_TYPE: {
    COMICS: 'FETCH_COMICS',
    CHARACTERS: 'FETCH_CHARACTERS'
  },
  FILTER_BY: 'FILTER_BY',
  FETCH_CHAR_BY_ID: 'FETCH_CHAR_BY_ID',
  FETCH_COMIC_BY_ID: 'FETCH_COMIC_BY_ID',
  SAVE_LOCATION: 'SAVE_LOCATION'
};
