export default {
  CONTENT_TYPE: {
    COMICS: 'FETCH_COMICS',
    CHARACTERS: 'FETCH_CHARACTERS'
  },
  FILTER_BY: 'FILTER_BY',
  FETCH_CHAR_BY_NAME: 'FETCH_CHAR_BY_NAME',
  FETCH_COMIC_BY_ID: 'FETCH_COMIC_BY_ID'
};
